# Generated by Django 3.2.13 on 2022-07-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3_upload.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(storage=s3_upload.storage_backends.MediaStorage(), upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('DisApproved', 'DisApproved')], default='Draft', max_length=20)),
                ('s3_bucket_url', models.CharField(default='', max_length=1000)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
