# Generated by Django 3.2.13 on 2022-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_dis_approve_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unpublish_reason',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('DisApproved', 'DisApproved'), ('UnPublished', 'UnPublished')], default='Draft', max_length=20),
        ),
    ]
